### ISSUE TITLE
Highlighting problems (tmLanguage)

### ISSUE THREAD

**Issue by beeb** [nvarner/typst-lsp#10]
It seems the syntax highlighting is not happy with the following shorthand syntax:

```
#show "Some String": box
```

```
#show "Some String": it => box[#it]
```

The `box` should be blue in both cases.

![image](https://user-images.githubusercontent.com/703631/227499471-783e19c8-5d2c-4e3a-a9d9-c7de7e6ffbf7.png)

**Comment by beeb** [comment]
Okay so we're not going to maintain our own here ig? I'll open an issue upstream

**Comment by beeb** [comment]
Another problem with highlighting: 

![image](https://user-images.githubusercontent.com/703631/227793064-58c944e2-5e96-48d6-8919-549d56b10d99.png)

**Comment by beeb** [comment]
Another one reported on [Discord](https://discord.com/channels/1054443721975922748/1087880600209342465/1089540532449054840):

Second line should not grey

![image](https://user-images.githubusercontent.com/703631/227793223-e2c5bb37-008f-4ff2-9436-979022978f8c.png)

**Comment by lf-** [comment]
This would plausibly all be fixed by using semantic highlighting computed server-side in the LSP server: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

One hazard of that though is that I'm not sure how resilient the parser is to doing an oopsie in the presence of incomplete syntax

**Comment by nvarner** [comment]
With the integration of semantic highlighting into v0.6, this should be fixed. Please reopen if not.
