### ISSUE TITLE
Cannot import .typ file from outer folder in workspace of VSCode anymore.

### ISSUE THREAD

**Issue by ivaquero** [nvarner/typst-lsp#255]
- **Component**: 
    - VSCode Extension
- **Extension version**: 0.9.4
- **LSP version**: 0.9.4
- **OS version and name**: macOS 13.5 Ventura

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

### Logs

Cannot import .typ file from outer folder in workspace of VSCode anymore after update to 0.9+.

<img width="726" alt="image" src="https://github.com/nvarner/typst-lsp/assets/46377665/79ed576b-6778-419a-b6f8-f318b33ba6b6">

```
[Error - 3:10:35 AM] src/server/lsp.rs:246 { message = could not handle source save; 
err = failed to generate document after compilation; 
uri = file://~/Documents/book-linear-algebra/09-%E5%87%A0%E4%BD%95%E5%8F%98%E6%8D%A2.typ; }
```

**Comment by nvarner** [comment]
Were you on 0.7 or earlier before updating to 0.9? If so, I think this is an (admittedly inconvenient) intentional behavior of Typst to keep files from importing other files outside the current package: https://github.com/typst/typst/issues/1664#issuecomment-1622395258

In the LSP, `root` is set based on your open workspace folders. If you open the parent directory, I think this will work as you expect. Alternatively, make `typst-styles` a [local package](https://github.com/typst/typst/issues/1664#issuecomment-1622395258). If those fixes don't work, or you were already running 0.8 or 0.9, then this is a bug.

**Comment by ivaquero** [comment]
I updated typst and typst-lsp at the same time, so I am not sure which this bug is for. My codes worked well before the update. 

I guess you are right, it's due to how `--root` treating the path.

**Comment by ivaquero** [comment]
I tried to compile using CLI, but it says `error: input file must be contained in project root.`. It seems this bug is on the typst side.

**Comment by ivaquero** [comment]
Hello again, @nvarner. Could you please consider adding a `--root` option in the VSCode Extension?

**Comment by Myriad-Dreamin** [comment]
@ivaquero https://github.com/nvarner/typst-lsp/blob/master/editors/vscode/package.json#L39
Does this option help?

**Comment by ivaquero** [comment]
Thank you so much! @Myriad-Dreamin

**Comment by ivaquero** [comment]
I tried to set `"typst-lsp.rootPath": ".."` or `"typst-lsp.rootPath": ${HOME}/Documents`, but it still doesn't work. Is the `rootPath` option is in accordance with `--root` in CLI?

**Comment by willismonroe** [comment]
I just tried adding `"typst-lsp.rootPath": "/",` to my settings.json and it seems not to respect the change.

**Comment by taooceros** [comment]
Same issue

**Comment by anesthetice** [comment]
same issue as well, also tried setting my TYPST_ROOT env-var but that doesn't seem to work either
