### ISSUE TITLE
Insufficient highlighting in neovim

### ISSUE THREAD

**Issue by sproott** [nvarner/typst-lsp#297]
- **Component**: 
    - LSP (used with other editor)
- **LSP version**: 0.9.5-1
- **OS version and name**: Arch Linux 6.5.3-arch1-1

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
Highlighting in neovim is almost non-existent compared to VSCode. I have tried different color schemes, but nothing works.

neovim:

![image](https://github.com/nvarner/typst-lsp/assets/46423131/08227152-73bd-4ae5-a1fe-6ac4d44a8634)

VSCode:

![image](https://github.com/nvarner/typst-lsp/assets/46423131/519d3570-bf25-445e-9dad-d5fa9cc0edfe)

**Comment by KillTheMule** [comment]
`typst-lsp` does send the necessary information though. Put you cursor on the `+`, run `:Inspect`, and you should be able to see that it's a semanctic token of type `@lsp.type.marker.typst`. It's just not highlighted because it does not have a highlight group set. Try, e.g. `lua vim.api.nvim_set_hl(0, '@lsp.type.marker.typst', { link = "Error", default = true })`, and it will be highlighted as an error. Doing this config properly isn't the job for the lsp. Maybe open a feature request at https://github.com/kaarmu/typst.vim for this.

**Comment by sproott** [comment]
I'm using [neovim-lspconfig](https://github.com/neovim/nvim-lspconfig) to set up the LSP, I don't have the plugin. But the LSP should be enough. I'm not sure how `neovim-lspconfig` handles highlighting, but I'll maybe just open an issue there and see if there's something to be done there.

**Comment by KillTheMule** [comment]
> But the LSP should be enough.

That's wrong. The LSP needs to send the token information, but doing the highlighting from that information is the job of the client.

> neovim-lspconfig

It doesn't. There's some blanket configuration in neovim itself (`runtime/lua/vim/lsp/semantic_tokens.lua`), but not in neovim-lspconfig. For some reason, the blanket configuration doesn't really apply here (I've no idea whey, seems to me the above should link to `Type`), but it's still a client problem, not a server problem.

**Comment by sproott** [comment]
Closing as the LSP server is working properly.
