### ISSUE TITLE
There is no language field exist in tokens/scopes when inspect in vscode

### ISSUE THREAD

**Issue by gRox167** [nvarner/typst-lsp#312]
- **Component**: 
    - VSCode Extension
- **Extension version**: v0.10.1
- **OS version and name**: macOS13.5.1 (22G90) and Windows 11

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
I start using typst-lsp from v0.3.2, and I update to the latest version recently. I find out that hypersnips extension doesn't work with typst-lsp normally, and this issue in hypersnips as a reference [https://github.com/draivin/hsnips/issues/176](Hypersnips). 
In previous version of typst-lsp, this `language` blank field is filled with `typst` as the name of the language.
<img width="530" alt="image" src="https://github.com/nvarner/typst-lsp/assets/40270265/add0e1c1-a8d5-40d3-9174-379bdc95cf7c">

**Comment by nvarner** [comment]
I've spent an hour or so investigating this, and I'm not sure how to set that language option. Unlike most languages, `typst-lsp` uses semantic tokens for syntax highlighting instead of a TextMate grammar, which comes with a lot of advantages. However, it's a slight abuse of the feature, and it isn't integrated as well into VS Code, so it may not be possible to set this without some trick.

Notably, `rust-analyzer` also uses semantic tokens, but does have this language set. I wasn't able to figure out how they do it, but if you (or someone else) has the interest to investigate, it should be possible to reverse engineer and figure out how it's done.

**Comment by gRox167** [comment]
Seems that in the v0.11.0, this problem is solved. Thanks for all of the work you have done @nvarner, this is really a perfect lsp for typst!
