### ISSUE TITLE
Docs: Compiling against Different Checkout of Typst

### ISSUE THREAD

**Issue by stellarpower** [nvarner/typst-lsp#330]
Hi,

I've updated my Typst version by building from source to get some new features (gradients!!!). However, this then means that whilst my standalone typst CLI can build these, previewing in VS Code is not able to compile these files.

Sometimes these VS Code/etc. extensions are talking to an installation elsewhere, but for the LSP server to be useful, I presume it needs programmatic access to that version of Typst => I need to rebuild the LSP, I can't point it to a path somewhere with a built library or binary.

Assuming this is the case, it'd be great if the docs in the readme could be updated please, to add a brief overview of how to build the LSP against a different version of the main typst repository. I see a tag is provided in the Cargo manifest, and I assume it could perhaps be as simple as bumping this, but as I'm not a Rustacean or much accustomed with language servers or VS Code extensions, I might be wrong.

I would guess that using a newer Typst version should make up a good proportion of reasons to build from source, if not working on the server itself, so feel a sentence or two just confirming how to do this would be appreciated by several folks.

Thanks!

**Comment by nvarner** [comment]
Your guesses are correct: the language server needs to be rebuilt with a new version of Typst, and the tag in `Cargo.toml` is what controls the version.

However, because Typst is still a new language, its API has changed with each release. So, in order to bump the version, you'll need to make changes to the `typst-lsp` source as well, which may be hard if you're not familiar with Rust. In short, it isn't necessarily easy to use the latest version, and it might stay that way until Typst becomes more stable.

That said, it's an easy thing to document, so I can include something about it.
