### ISSUE TITLE
Some advice

### ISSUE THREAD

**Issue by jiandwei** [nvarner/typst-lsp#355]

**Comment by nvarner** [comment]
I'd love to include this in the documentation so other Emacs users can find it. A few notes on that:
- I don't know Emacs configuration, so this may have an obvious answer. I see a URL (https://git.sr.ht/~meow_king/typst-ts-mode/) that stands out to me; what is this for, and how can users know it's trustworthy?
- Can you submit a PR to put this in the docs? Otherwise, do you have the copyright, and will you grant the license, so that I can include it in the docs?

**Comment by andreyyao** [comment]
- The url appears to be a link to `typst-ts-mode`. It is one of the only current emacs major mode implementations for `typst`. Major modes in emacs are like "extensions" in other editors. Since typst is quite new, there isn't a major mode for typst inside the more "official" emacs repositories. I can't speak for any security guarantees for that repo, but it's probably fine.
- The rest of the Elisp code is standard, basically instructing `lsp-mode` (an emacs lsp client) to connect to `typst-lsp` whenever a file with extension `.typ` is opened.
